### ISSUE TITLE
What should I do with fast-moving videos?

### ISSUE THREAD

**Issue by timbuktu031** [AdamSpannbauer/python_video_stab#112]
Hi~
I want to apply this to a video shot with a racing drone.
so movement is fast. 
I tried converting it without using any options.

https://youtu.be/3SsQxaArs-U

Which option is best to make the possible black margins invisible?
Is it possible that the stabilized images is always in the center of the screen?

**Comment by AdamSpannbauer** [comment]
Hi @timbuktu031 

> Which option is best to make the possible black margins invisible?

You can check out the [using borders](https://github.com/AdamSpannbauer/python_video_stab#using-borders) section of the README for different options you have for the margins.

> Is it possible that the stabilized images is always in the center of the screen?

Not really, the whole way that it is performing the stabilization is by moving the image around to try and keep the contents of the image in the same spot.  (i.e the camera shifted but to keep the trees in the frame in the same spot, the image would need to be moved.

**Comment by AdamSpannbauer** [comment]
Please re-open if this if my response doesn't address your issue adequately.
