### ISSUE TITLE
installing vidstab from pypi or github

### ISSUE THREAD

**Issue by henry-oconnor** [AdamSpannbauer/python_video_stab#12]
I'm having trouble installing vidstab with pip. This is the error message:

Collecting git+https://github.com/AdamSpannbauer/python_video_stab.git
  Cloning https://github.com/AdamSpannbauer/python_video_stab.git to c:\users\henoc\appdata\local\temp\pip-req-build-cb124koo
Requirement already satisfied: numpy in c:\python34\lib\site-packages (from vidstab==0.1.6) (1.14.5)
Collecting pandas (from vidstab==0.1.6)
  Using cached https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
  **Could not find a version that satisfies the requirement numpy==1.9.3 (from versions: 1.10.4, 1.11.0, 1.11.1rc1, 1.11.1, 1.11.2rc1, 1.11.2, 1.11.3, 1.12.0b1, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.15.0rc1)
No matching distribution found for numpy==1.9.3**

I'm using python 3.4.3, opencv 3.4.1, numpy 1.14.5 and pip 10.0.1.

**Comment by AdamSpannbauer** [comment]
Are you able to install pandas on its own using `pip install pandas`?

**Comment by henry-oconnor** [comment]
Ah, I was misreading the error message. Turns out pandas doesn't support python 3.4. Got it installed, thanks for your help.

**Comment by AdamSpannbauer** [comment]
Glad you got it working. The next major release is planned to remove pandas as a dependency.

I’m going to go ahead and close this issue.
