### ISSUE TITLE
what's the name of the trajectory smoothing of this project?

### ISSUE THREAD

**Issue by LS11111** [AdamSpannbauer/python_video_stab#127]
i want to know more about this mathematical method,thank you very much.

**Comment by AdamSpannbauer** [comment]
The smoothing is done with a moving average

**Comment by LS11111** [comment]
Thank you for your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adam ***@***.***&gt;; 
发送时间: 2021年11月14日(星期天) 晚上7:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AdamSpannbauer/python_video_stab] what&#39;s the name of the trajectory smoothing of this project? (Issue #127)





 
The smoothing is done with a moving average
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
