### ISSUE TITLE
 transformation + (smoothed_trajectory – trajectory)?

### ISSUE THREAD

**Issue by LS11111** [AdamSpannbauer/python_video_stab#128]
Why design the transformation matrix this way?What does smoothed_trajectory – trajectory stands for?

**Comment by AdamSpannbauer** [comment]
Thanks for closing this issue as these questions aren't the type of thing issues are intended for.  Please see the [README](https://github.com/AdamSpannbauer/python_video_stab#readme) for questions like this:

> Python video stabilization using OpenCV. Full searchable documentation here.
>
> This module contains a single class (VidStab) used for video stabilization. This class is based on the work presented by Nghia Ho in [SIMPLE VIDEO STABILIZATION USING OPENCV](http://nghiaho.com/?p=2093). The foundation code was found in a comment on Nghia Ho's post by the commenter with username koala.
