### ISSUE TITLE
videostab on realtime videos

### ISSUE THREAD

**Issue by rijutawankar** [AdamSpannbauer/python_video_stab#13]
I am trying to apply this algorithm on a real time camera feed with the help of opencv library, I am unable to do cv2.imshow for input as well as output videos. Is the class Vidstab not supported for realtime videos.

**Comment by AdamSpannbauer** [comment]
Please see #6.  My last comment there goes into a little detail about the planned timeline and some caveats about 'real time'.

I am closing this issue since it is covered in #6.
