### ISSUE TITLE
Non-free algorithms like SIFT and SURF causing tests to fail.

### ISSUE THREAD

**Issue by RobRoseKnows** [AdamSpannbauer/python_video_stab#20]
See skvark/opencv-python#126. As of OpenCV 3.4.3, the patented algorithms such as SIFT and SURF are hidden behind the `OPENCV_ENABLE_NONFREE=1` flag. They are no longer included in the Python bindings which is causing the tests to fail on Travis.

Possible options are:
- Remove SIFT and SURF from the tests
- Add try-except logic in kp_method initialization to raise a warning when SIFT and SURF are used.

**Comment by AdamSpannbauer** [comment]
Thanks for the catch, I had forgotten to turn on a recurring Travis build (turned on now).

Fix to come.

**Comment by AdamSpannbauer** [comment]
SIFT and SURF dropped from tests and a note about them has been added to the docs

thanks again for the catch @RobRoseKnows
