### ISSUE TITLE
Fix delta angle plot issues around degrees/radians

### ISSUE THREAD

**Issue by Molier** [AdamSpannbauer/python_video_stab#32]
Appreciate the work and the progress, can't wait to see the upcoming features, like the auto border.

I can't figure out what unit the rotation is in, it says "degrees" on the axis but that doesn't seem to be true. Eg. in the following screenshot:

![image](https://user-images.githubusercontent.com/7408635/46826838-571bde00-cd97-11e8-9d00-a2a91cb889be.png)

The image is rotated 5° to the counterclockwise, which corresponds to 0,0872 radians. The graph displays -0.18. What's going on here?

**Comment by AdamSpannbauer** [comment]
Hi @Molier!  I'm not a place where I can triple check everything, but I believe that 'degrees' is correct.

You mention that the "image is rotated 5° to the counterclockwise".  Is the 5° you report relative to the images starting angle or relative to the previous frame's angle?

**Comment by AdamSpannbauer** [comment]
Hi @Molier, anything to report back on this?

**Comment by AdamSpannbauer** [comment]
I still haven't had time to review this in the depth it deserves.  I am feeling less confident about my initial answer.

Hope to review this soon and add an option to plot in rad or degrees.  Thanks for opening the issue @Molier

**Comment by AdamSpannbauer** [comment]
@Molier I am renaming this issue to better reflect it as a work item.  You found a bug in the package.  

The plot is plotting the rotations used while stabilizing in radians despite being labeled as degrees.

I will update progress here.

**Comment by AdamSpannbauer** [comment]
#35 adds fixes the mislabelling of plot and adds option to plot in radians or degrees using the `radians` argument (default `radians=False`)

@Molier I will be merging #35 assuming CI passes.  I think that this PR closes your issue, but I will give you some time to respond.  If I haven't heard anything in a few days I will close this issue.

**Comment by AdamSpannbauer** [comment]
@Molier I am closing this issue.  If you feel that it should be reopened please let me know
