### ISSUE TITLE
AttributeError: GFTT not a supported detector

### ISSUE THREAD

**Issue by jinfagang** [AdamSpannbauer/python_video_stab#46]
Just wonder it could be done...........

**Comment by AdamSpannbauer** [comment]
Can you elaborate?

Are you talking about the black edge that occurs like in this frame below?

<img src='https://user-images.githubusercontent.com/16326083/48334257-d870c580-e60e-11e8-8c02-bae382cdf8b9.png' width = 40%>

If so there are some options built into the package.  See [Using borders](https://github.com/AdamSpannbauer/python_video_stab#using-borders) section of readme.

![image](https://user-images.githubusercontent.com/16326083/48334342-2b4a7d00-e60f-11e8-9026-b0d53aa6ae2e.png)

**Comment by jinfagang** [comment]
@AdamSpannbauer Thank u Sir. I just notice this. But when I try stab an video, error says:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/imutils/feature/factories.py", line 81, in FeatureDetector_create
    detr = _DETECTOR_FACTORY[detector.upper()]
KeyError: 'GFTT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "debounce.py", line 12, in <module>
    stabilizer = VidStab()
  File "/usr/local/lib/python3.6/dist-packages/vidstab/VidStab.py", line 74, in __init__
    blockSize=3)
  File "/usr/local/lib/python3.6/dist-packages/imutils/feature/factories.py", line 86, in FeatureDetector_create
    raise AttributeError("{} not a supported detector".format(detector))
AttributeError: GFTT not a supported detector

```

I am using python3.6.

```
import os
from vidstab import VidStab


stabilizer = VidStab()
stabilizer.stabilize(input_path='video/combined_ros_bag_video.mp4.mp4',
                     output_path='video/combined_ros_bag_video_stab.mp4', playback=True)
```

**Comment by AdamSpannbauer** [comment]
This is related to an apparent issue in `VidStab`'s `imutils` dependency and your OpenCV installation.

The `'GFTT'` keypoint detector is currently only available through `imutils` if your OpenCV installation included [`opencv_contrib`](https://github.com/opencv/opencv_contrib).  The `'GFTT'` detector shouldn't require contrib modules, but it is required the way `imutils` currently handles it.  I am filing a PR and hopefully we can have it fixed soon.

In the meantime you should be able to fix your error by:

#### Installing OpenCV + contrib

If you are working with the precompiled [`opencv-python`](https://pypi.org/project/opencv-python/) available on PyPi, then I've noted how I was able to overcome this exception when I ran into it in [this issue](https://github.com/AdamSpannbauer/python_video_stab/issues/4#issuecomment-383648375).

If you prefer to build OpenCV from source then you will need to research the appropriate way to build OpenCV with the contrib modules on your OS.

#### Using a different keypoint detector

Available detectors when using `imutils` without `opencv_contrib` are: `"MSER"`, `"FAST"`, `"BRISK"`, & `"ORB"`

To specify the keypoint method using `VidStab` use the below example syntax.

```python
from vidstab import VidStab

stabilizer = VidStab(kp_method='FAST')
```

**Comment by AdamSpannbauer** [comment]
The PR to address this issue has been accepted/merged into `imutils`.  I will wait to close this issue until the updated `imutils` is released to PyPi.

**Comment by AdamSpannbauer** [comment]
`imutils 0.5.2` is now on PyPi with a fix for this issue
