### ISSUE TITLE
module 'cv2' has no attribute 'estimateRigidTransform'

### ISSUE THREAD

**Issue by JolleJolles** [AdamSpannbauer/python_video_stab#49]
I get above error message in python 3, do you know how to fix this? thanks

**Comment by AdamSpannbauer** [comment]
What version of OpenCV are you running?

**Comment by AdamSpannbauer** [comment]
To follow-up on this.  The package is tested with [`opencv-contrib-python`](https://pypi.org/project/opencv-contrib-python/).  If you can, my suggestion would be to create a virtualenv and run `pip install vidstab[cv2]` to install both `vidstab` and `opencv-contrib-python`.

Of note, you'll inevitably run into issues if you `pip install opencv-contrib-python` into an environment where you already have a manually built OpenCV installed.  This is a possible reason for your issue, but impossible to know with the current information provided.

Please let me know if you're running OpenCV `4.0.0`.  I have not yet tested the package with this new release.  If you're running a manually built OpenCV < `4.0.0` then your issue might be related to your specific build.

**Comment by AdamSpannbauer** [comment]
@JolleJolles Please re-open this issue and add additional information if this is still a relevant problem.
