### ISSUE TITLE
Process live video

### ISSUE THREAD

**Issue by AdamSpannbauer** [AdamSpannbauer/python_video_stab#6]
Look into processing live streaming video (i.e. webcam) as brought up by [TomGKomar on twitter](https://twitter.com/TomGKomar/status/1001488057676304387).

**Comment by TopperBG** [comment]
Will be that feature realized near feature ?

**Comment by AdamSpannbauer** [comment]
Hi @TopperBG.  Yes, I hope to have to have the live video feature up within the next week or so.

I have the back end logic to process live video working.  It needs some polishing up, additional tests,  and documentation.  I also need to make some decisions on how this will affect the current API.

__A possible point of interest__:
The stabilization process requires an `n` frame smoothing window, so there is an inherent `n` frame delay in processing 'live' video.  The smoothing window can be lessened to get closer to real time output, but very small smoothing windows can result in poorer stabilization output.

**Comment by TopperBG** [comment]
Latency is good known sacrifice for stabilization of video, so ... go on :+1:

**Comment by AdamSpannbauer** [comment]
going to close since #17 covers the remaining documentation issue
