### ISSUE TITLE
Pass stabilized video frame for further processing

### ISSUE THREAD

**Issue by pranavlal** [AdamSpannbauer/python_video_stab#67]
Hi,
I want to pass stabilized video for further processing such as sending it to an object detector. Is there a way to do this? I ask because in the input method, I only see outputting the stabilized video to a file.

**Comment by AdamSpannbauer** [comment]
Hi @pranavlal,

Thanks for reporting the issue.

This type of processing will be possible once #50 is resolved.  I will update that thread when I get some time to work on the issue.  I'm going to close this issue to cut down on the duplication.

Thanks!

**Comment by pranavlal** [comment]
Thanks, I understand. I'll keep track and let me know if I can help with testing.
