### ISSUE TITLE
Is it possible used for video shake detection?

### ISSUE THREAD

**Issue by cscyangj** [AdamSpannbauer/python_video_stab#68]

**Comment by AdamSpannbauer** [comment]
Sorry for the delay in responding.  In theory, it could be used for shake detection, but I believe it would be pretty susceptible to noise (i.e. something moving in the image rather the image moving).

To test it out you can put video through the `VidStab.gen_transforms()` method (see [this section of the README](https://github.com/AdamSpannbauer/python_video_stab#generating-and-saving-transforms-to-file) for example).  If the contents  of the `VidStab.transforms` attribute are zeros then no transformations would be applied (i.e. no shake detected).  However, as stated before, I'm not sure how well this will work.

**Comment by hongjundai** [comment]
some error
File "/usr/local/lib/python3.5/dist-packages/vidstab-1.6.1-py3.5.egg/vidstab/VidStab.py", line 263
    raise FileNotFoundError(f'{input_path} does not exist')
help!!

**Comment by AdamSpannbauer** [comment]
@hongjundai what code did you run that caused the error?  Are you sure that the video you tried to process exists in the location your code said it did?
