### ISSUE TITLE
the paper of the algorithm 

### ISSUE THREAD

**Issue by 1earner** [AdamSpannbauer/python_video_stab#75]
This work is awesome. Would you like to share the detail of this algorithm or the paper of this algorithm?

**Comment by AdamSpannbauer** [comment]
An overview of the algorithm can be found in the below-quoted sentence from the README.

> This class is based on the work presented by Nghia Ho in [SIMPLE VIDEO STABILIZATION USING OPENCV](http://nghiaho.com/?p=2093).

**Comment by 1earner** [comment]
@AdamSpannbauer Thank you very much
