### ISSUE TITLE
8uC1 or 8uC3

### ISSUE THREAD

**Issue by mrsahabu** [AdamSpannbauer/python_video_stab#76]
When I am running test video, I am not getting any error but when I pass my desired video it gives this error "error: (-210) Both input images must have either 8uC1 or 8uC3 type in function cv::estimateRigidTransform"

I am using Python 3 and openCV 3.1.4.

**Comment by AdamSpannbauer** [comment]
Hi @mrsahabu, thanks for reporting the issue.

Could you please provide the code snippet that you are trying to run?  And if possible, could you share the video that's causing the issue? I understand if you'd rather not, but I haven't been able to reproduce the issue with my test videos.  If you're ok with sharing the video, but would rather not do so in a public forum you can [email it to me](mailto:spannbaueradam@gmail.com).

---

FYI if you're curious about the error (and you didn't already understand).  For some reason, a grayscale image and a BGR image are being compared (or another 3 color channel format).  OpenCV's data type descriptors (i.e. `8uC1`) are of the format:

```
CV_<number_of_bits_per_channel><Unsigned/Signed/Float>C<number_of_channels>
```

**Comment by mrsahabu** [comment]
Hi @AdamSpannbauer  Thanks for your quick response, really appreciated. 
Below is the code I am using:
#########################################################################
from vidstab.VidStab import VidStab
import cv2
import numpy as np
videoName='y2mate'
extension='.mp4' 

filename = 'D:\\Tennis\\Videos\\'+videoName+extension

stabilizer = VidStab()
vidcap = cv2.VideoCapture(filename)
while True:
    grabbed_frame, frame = vidcap.read()

    if frame is not None:
        # Perform any pre-processing of frame before stabilization here
        pass
    



     # Pass frame to stabilizer even if frame is None
     # stabilized_frame will be an all black frame until iteration 30
    stabilized_frame = stabilizer.stabilize_frame(input_frame=frame,smoothing_window=15)
     
    if stabilized_frame is None:
         break
     
    cv2.imshow('stabilized_frame',stabilized_frame)
    cv2.waitKey(1)
     
  
     # Perform any post-processing of stabilized frame here
##############################################################################
The video I am using is any Tennis match video from youtube. Actually I am doing Tennis Court Top view Registration. I tried to debug it myself and reached that the  Curr_Matched_KP, Matched_Keypoints are null. I think there is issue with Video may be it is already stabled? 

Thanks Again!!

**Comment by AdamSpannbauer** [comment]
@mrsahabu, hope you don't mind that I edited your comment (formatted the code for easier viewing).

I've got a couple more questions to make sure I understand how to reproduce the error and debug.

* Is there a particular YouTube video that is causing the error?  Or has every video you've downloaded from YouTube caused the issue?
* How are you downloading the YouTube videos?  If you are using a python script to do this would you mind sharing so I follow the same process? (If you'd rather not share your code then passing along the library you're using should suffice)
* Have you verified the downloaded YouTube videos are playing normally after download? (in VLC or whatever is your local video player of choice)

**Comment by mrsahabu** [comment]
Sorry  for late.

- Every video I downloaded from youtube gives error.
- I am downloading videos using this https://y2mate.com/ .
- Yes! These are working on VLC/Windows Media Player.

**Comment by AdamSpannbauer** [comment]
Thanks for all the info @mrsahabu.  This weekend I'll do my best to recreate your issue and figure out a fix.

**Comment by seventheefs** [comment]
Hi, I get the same error. 

- When i launch my usb camera i get:
"The error starts with VIDEOIO ERROR: V4L2: getting property #7 is not supported."

After a few seconds, i get a preview of my camera with the progress bar. A few moments later i get the following error: "error: (-210) Both input images must have either 8uC1 or 8uC3 type in function cv::estimateRigidTransform".

- My second question is about using your code with picamera. Somehow i'm unable to make it work with it, i tried the -i -1 parameter but it just keep displaying the FileNotFoundError: -1 does not exist.

**Comment by AdamSpannbauer** [comment]
@mrsahabu First off I apologize for the delay in getting back to you.  Unfortunately, I was unable to recreate your error using the below script with a video downloaded with y2mate (exact video link in a comment in below code chunk).

I did find/fix some bugs and I've pushed fixes for them to the branch [`channel_bug_76`](https://github.com/AdamSpannbauer/python_video_stab/tree/channel_bug_76).  Would you try installing that branch's version of vidstab and try processing your video(s) to see if fixing those bugs addresses your issue?

You can install the dev version in question with the below command.

```
pip install git+https://github.com/AdamSpannbauer/python_video_stab.git@channel_bug_76
```

---

Code used to try and reproduce

```python
import sys
import vidstab
import cv2

print(f'\n{sys.version}\n')
print(f'vidstab version: {vidstab.__version__}')
print(f'cv2 version:     {cv2.__version__}')

# Some random youtube video with a Creative Commons license
# https://www.youtube.com/watch?v=VtsYNIJZDFU
# Downloaded with y2mate
filename = 'y2mate_video.mp4'

stabilizer = vidstab.VidStab()
vidcap = cv2.VideoCapture(filename)
while True:
    grabbed_frame, frame = vidcap.read()

    if frame is not None:
        cv2.imshow('input_frame', frame)
        pass

    stabilized_frame = stabilizer.stabilize_frame(input_frame=frame,
                                                  smoothing_window=15)

    if stabilized_frame is None:
        break

    cv2.imshow('stabilized_frame', stabilized_frame)
    cv2.waitKey(1)
```

Console output

```
3.6.5 (default, Apr  2 2018, 18:15:50) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

vidstab version: 1.6.2
cv2 version:     4.0.0
```

**Comment by mrsahabu** [comment]
Hi @AdamSpannbauer  Thanks for your detailed answer. I will check this on weekend. Thanks again.

**Comment by AdamSpannbauer** [comment]
Hi @mrsahabu, any update on this?  No rush if not; I'm just checking in on all open issues.

**Comment by mrsahabu** [comment]
Hi @AdamSpannbauer  Sorry I was not able to check it. Because My project requirements full filled without this. By the way Thanks for your effort. Your work is great. I am closing this issue.
