### ISSUE TITLE
picamera FileNotFoundError

### ISSUE THREAD

**Issue by AdamSpannbauer** [AdamSpannbauer/python_video_stab#78]
Below quote taken from @seventheefs comment on #76 

> My second question is about using your code with picamera. Somehow i'm unable to make it work with it, i tried the -i -1 parameter but it just keep displaying the FileNotFoundError: -1 does not exist. i'm using opencv 3.4.2 with a pycamera rev 1.3

**Comment by AdamSpannbauer** [comment]
@seventheefs I believe I've found the root cause of the issue and I've pushed a fixed.  I don't have easy access to picamera right now.  Would you be able to test the fix and report back if it resolved your issue?

The fix is live in version 1.7.1

**Comment by AdamSpannbauer** [comment]
Hi @seventheefs, any update on this?  No rush if not; I'm just checking in on all open issues.

**Comment by seventheefs** [comment]
hi thanks for asking, i am in a trip right now so i couldn't verify it. Will be back to you on this next week. till then, take care.

**Comment by AdamSpannbauer** [comment]
@seventheefs I'm going to close this due to inactivity. please re-open if the issue still persists
