### ISSUE TITLE
Error: SintaxError: invalid syntax on Raspberry Pi 3 B+ Python 3.5.3

### ISSUE THREAD

**Issue by MaulyGabriel** [AdamSpannbauer/python_video_stab#92]
I found a syntax error, even editing the file the error remains.

**Comment by AdamSpannbauer** [comment]
Can you please provide the code you attempted to run and the traceback of the exception?

**Comment by AdamSpannbauer** [comment]
Hi @MaulyGabriel, I just wanted to inform you that if you're unable to provide a way to recreate the error then I'll close this issue within about a week's time.

**Comment by AdamSpannbauer** [comment]
Hi, @MaulyGabriel, last call on providing some additional info on the issue.  I plan to close it tomorrow if I don't hear anything back.
