### ISSUE TITLE
Audio missing from stabilized file

### ISSUE THREAD

**Issue by prasadbrg** [AdamSpannbauer/python_video_stab#93]
`from vidstab import VidStab`

`# Using defaults`
`stabilizer = VidStab()`
`stabilizer.stabilize(input_path='input_video.mov', output_path='stable_video.avi')`

I used this code in the documentation, with `input_path` pointing to a .MOV file. The stabilized video did not have any audio in it. Repeated with an mp4 - converted version of the same file, and again audio was missing.

Is this expected behaviour? If not, are there any workarounds until the issue is fixed? 

Thanks in advance.

**Comment by AdamSpannbauer** [comment]
Unfortunately, that is expected behavior.  I've opened #94 as a feature request for this so you don't have to get bombarded with notifications.  I'm going to go ahead and mark this issue as closed.   I'll ping this issue when/if audio support is added via #94
